#!/bin/bash -v

DB_NAME=sandoz_bbmb

yyyy=`date -d '1 days ago' +"%Y"`
mm=`date -d '1 days ago' +"%m"`
dd=`date -d '1 days ago' +"%d"`
DB_DUMP=/var/backup/fast/db_dumps/sandoz_bbmb.$yyyy$mm$dd.sql.gz


m=(dummy January February March April May June July August September October November December)
nm=`expr $mm + 0`
cd /var/backup/fast/db_dumps/
cmd="scp ngiger@62.12.131.46:/var/backup/fast/db/postgresql/${m[nm]}-$yyyy/$yyyy-$mm-$dd/22\:00-postgresql_database-sandoz_bbmb-backup.gz sandoz_bbmb.$yyyy$mm$dd.sql.gz"
echo Calling $cmd
$cmd
ls -l $DB_DUMP
sudo -u postgres dropdb $DB_NAME

sudo -u postgres createdb -E UTF8 -T template0 $DB_NAME
if [ $? -ne 0 ] ; then exit 1; fi
if [ ! -f $DB_DUMP ] 
then
  echo "Cannot find $DB_DUMP. Have look at the get_db_dumps.rb script or get it directly from"
  exit 1
fi

sudo -u postgres psql -c "create user sandoz with UNENCRYPTED password 'sandoz';"
sudo -u postgres psql -c "alter user sandoz with UNENCRYPTED password 'sandoz';"
sudo -u postgres psql -c "grant all privileges on database $DB_NAME to sandoz ;"
sudo -u postgres psql -c 'create role apache with LOGIN;'
sudo -u postgres psql -c "create role $DB_NAME with LOGIN;"

zcat $DB_DUMP | sudo -u postgres psql $DB_NAME
if [ $? -ne 0 ] ; then exit 1; fi
