#!/bin/bash
DB_NAME=sandoz_bbmb
DAYS_AGO=1
yyyy=`date -d "$DAYS_AGO days ago" +"%Y"`
mm=`date -d "$DAYS_AGO days ago" +"%m"`
dd=`date -d "$DAYS_AGO days ago" +"%d"`
DB_DUMP=/var/backup/fast/db_dumps/$DB_NAME.$yyyy$mm$dd.sql.gz


m=(dummy January February March April May June July August September October November December)
nm=`expr $mm + 0`
cd /var/backup/fast/db_dumps/
cmd="scp ngiger@62.12.131.46:/var/backup/fast/db/postgresql/${m[nm]}-$yyyy/$yyyy-$mm-$dd/22\:00-postgresql_database-${DB_NAME}-backup.gz ${DB_DUMP}"
if [ ! -f $DB_DUMP ]; then
  echo Calling $cmd
  $cmd
fi
ls -l $DB_DUMP
if [ $? -ne 0 ] ; then exit 1; fi

# echo "sudo -u postgres createdb -E UTF8 -T template0 $DB_NAME"
# echo "zcat $DB_DUMP | sudo -u postgres psql $DB_NAME"

sudo -u postgres dropdb $DB_NAME

sudo -u postgres createdb -E UTF8 -T template0 $DB_NAME
if [ $? -ne 0 ] ; then exit 1; fi
if [ ! -f $DB_DUMP ]
then
  echo "Cannot find $DB_DUMP. Have look at the get_db_dumps.rb script or get it directly from"
  exit 1
fi

sudo -u postgres psql -c "create user sandoz with UNENCRYPTED password 'sandoz';"
sudo -u postgres psql -c "alter user sandoz with UNENCRYPTED password 'sandoz';"
sudo -u postgres psql -c "grant all privileges on database $DB_NAME to sandoz ;"
sudo -u postgres psql -c 'create role apache with LOGIN;'
sudo -u postgres psql -c "create role $DB_NAME with LOGIN;"

zcat $DB_DUMP | sudo -u postgres psql $DB_NAME
if [ $? -ne 0 ] ; then exit 1; fi
